// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl0N2PKyrtP6EEx39iG5-jz6qoNc4-ch4',
    appId: '1:959203497833:web:112287ea61270b50f48ff8',
    messagingSenderId: '959203497833',
    projectId: 'agrotalk-7c291',
    authDomain: 'agrotalk-7c291.firebaseapp.com',
    storageBucket: 'agrotalk-7c291.appspot.com',
    measurementId: 'G-QR36FTRXCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhL5vLe8ccchVy2yXgM5xZKFLAE0_giE',
    appId: '1:959203497833:android:39af93651b009da4f48ff8',
    messagingSenderId: '959203497833',
    projectId: 'agrotalk-7c291',
    storageBucket: 'agrotalk-7c291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TxjfHXU58d0AxhDiZYHIvVCEFBxhPTs',
    appId: '1:959203497833:ios:95cd1b503e96cd73f48ff8',
    messagingSenderId: '959203497833',
    projectId: 'agrotalk-7c291',
    storageBucket: 'agrotalk-7c291.appspot.com',
    iosClientId: '959203497833-mspsd9gii21ijnlkc7p4n02cvd0f9san.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrotalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_TxjfHXU58d0AxhDiZYHIvVCEFBxhPTs',
    appId: '1:959203497833:ios:95cd1b503e96cd73f48ff8',
    messagingSenderId: '959203497833',
    projectId: 'agrotalk-7c291',
    storageBucket: 'agrotalk-7c291.appspot.com',
    iosClientId: '959203497833-mspsd9gii21ijnlkc7p4n02cvd0f9san.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrotalk',
  );
}
